baseurl = "/"
title = "Dr. Grant Alexander Wilson"
copyright = "Dr. Grant Alexander Wilson, 2021"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "hey"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
disqusShortname = ""
googleAnalytics = "G-CG5Y0L06K"
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
enableGitInfo = false

[outputs]
home = ["HTML", "CSS", "RSS"]
section = ["HTML", "RSS"]

[blackfriday]
fractions = true
hrefTargetBlank = true
smartypants = true

[params]
address = "Room 52 25 Campus Drive, Nutrien Centre, University of Saskatchewan Saskatoon, Saskatchewan, S7N 5A7 Canada"
avatar = "/img/image01.jpg"
color_theme = "ocean"
comment_count = false
custom_css = ["@import url(\"https://use.typekit.net/ffm5ass.css\");"]
custom_js = []
date_format = "2006-01-02"
email = "contact@grantwilson.ca"
font = "classic"
gravatar = false
highlight = true
highlight_languages = []
keybase = ""
latitude = "52.133400"
logo = ""
longitude = "-106.631355"
map = "2"
map_api_key = "pk.eyJ1IjoiYWxleGpzdGVmZmVuIiwiYSI6ImNrazd2YmF5NDBoczAydm83M3QwYmx5ZmEifQ.PboSv3yxefBxjO_au1F6Tw"
math = false
name = "Grant Alexander Wilson"
office_hours = "By Appointment"
phone = "+1 306 966 5583"
privacy_pack = false
publication_types = ["Uncategorized", "Conference paper", "Journal article", "Manuscript", "Report", "Book", "Book section"]
reading_time = true
role = "Faculty Member, Department of Management and Marketing"
section_pager = false
sharing = false
skype = ""
telegram = ""
time_format = "3:04 PM"
zoom = 15

[params.menus]
align_right = true

[[params.organizations]]
name = "University of Sasktchewan, Edwards School of Business"
url = "edwards.usask.ca"

[params.projects]
list_children = false
publication_format = 3

[[params.social]]
icon = "envelope"
icon_pack = "fa"
link = "mailto:test@example.org"

[[params.social]]
icon = "twitter"
icon_pack = "fa"
link = "//twitter.com/GeorgeCushen"

[[params.social]]
icon = "google-scholar"
icon_pack = "ai"
link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

[params.talks]
time = true

[menu]

[[menu.main]]
name = "Home"
url = "#about"
weight = 1

[[menu.main]]
name = "Publications"
url = "#publications"
weight = 2

[[menu.main]]
name = "Teaching"
url = "#teaching"
weight = 5

[[menu.main]]
name = "Talks"
url = "#talks"
weight = 6

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

[[menu.main]]
name = "Consulting"
url = "#consulting"
weight = "8"

[taxonomies]
category = "categories"
publication_type = "publication_types"
tag = "tags"

[Languages]

[Languages.en]
languageCode = "en-ca"